apiVersion: v1
kind: Service
metadata:
  name: flask-bank-app-service
spec:
  selector:
    app: flask-bank-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
