apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-bank-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-bank-app
  template:
    metadata:
      labels:
        app: flask-bank-app
    spec:
      containers:
      - name: flask-app
        image: karankolhe099 / flask-bank-appp
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: application.py
        - name: FLASK_ENV
          value: production

